server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/promtail/positions-performance.yaml

clients:
  - url: http://10.0.0.72:3100/loki/api/v1/push

scrape_configs:
  - job_name: spring-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          env: performance
          __path__: /log/**/*.log
