spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${database.prod.url}
    username: ${database.prod.username}
    password: ${database.prod.password}
  sql:
    init:
      mode: never
      schema-locations:
      data-locations:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false

  flyway:
    enabled: true
    user: ${database.prod.username}
    password: ${database.prod.password}
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    out-of-order: false
    encoding: UTF-8

  config:
    activate:
      on-profile: prod
    import:
      - submodule/security/database.yml

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
