spring:
  profiles:
    active: local
  config:
    import:
      - submodule/security/aladin.yml
      - submodule/security/jwt.yml

aladin:
  base-url: ${aladin.base-url}
  item-search-uri: ${aladin.item-search-uri}
  api-key: ${aladin.api-key}
  item-lookup-uri: ${aladin.item-lookup-uri}

jwt:
  secret-key: ${jwt.secret-key}
  access-token:
    expire-mills: ${jwt.access-token.expire-mills}
  temp-token:
    expire-mills: ${jwt.temp-token.expire-mills}
