version: '3.8'

services:
  prod:
    container_name: "prod_${ENV_ID}"
    image: woowajeff/todoktodok:prod
    ports:
      - "80:8080"
    volumes:
      - ../log:/log
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always

  promtail:
    container_name: "promtail_prod_${ENV_ID}"
    image: grafana/promtail:latest
    volumes:
      - ../config/promtail-config-prod.yml:/etc/promtail/promtail.yml
      - ../log:/log
      - ../promtail_data:/var/log/promtail
    command: -config.file=/etc/promtail/promtail.yml
    restart: always

volumes:
  promtail_positions:
