version: '3.8'

services:
  dev:
    container_name: dev
    build:
      context: ..
      dockerfile: ../Dockerfile.dev
      args:
        JAR_FILE: /build/libs/*.jar
    image: woowajeff/todoktodok:dev
    ports:
      - "80:8080"
    volumes:
      - ../log:/log
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: always
    networks:
      - dev_network

  promtail:
    container_name: promtail_dev
    image: grafana/promtail:latest
    ports:
      - "9080:9080"
    volumes:
      - ../config/promtail-config-dev.yml:/etc/promtail/promtail.yml
      - ../log:/log
    command: -config.file=/etc/promtail/promtail.yml
    restart: always
    networks:
      - dev_network

networks:
  dev_network:
    external: true
