spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${database.practice.url}
    username: ${database.practice.username}
    password: ${database.practice.password}
  sql:
    init:
      mode: never
      schema-locations:
      data-locations:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false

  flyway:
    enabled: true
    user: ${database.practice.username}
    password: ${database.practice.password}
    locations:
      - classpath:db/migration_dev
      - classpath:db/seed_dev
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    encoding: UTF-8

  config:
    activate:
        on-profile: practice
    import:
      - submodule/security/database.yml
      - submodule/security/firebase.yml

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: false
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: false

firebase:
  enabled: false
  account:
    path: ${firebase.account.path}

jwt:
  access-token:
    expire-mills: ${jwt.access-token.dev.expire-mills}

database:
  fragmentation-check:
    enabled: true
    cron: "0 0 3 * * *"
