name: Backend CI/CD

on:
  push:
    branches: [ "practice" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./backend

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.SECRETS_SUBMODULE_ACCESS_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Clean Project
        run: ./gradlew clean

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Assemble Build
        run: ./gradlew build

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_DEPLOY_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEPLOY_TOKEN }}

      - name: Docker Image Build & Push
        run: |
          docker buildx build -f Dockerfile.dev --platform linux/arm64 -t woowajeff/todoktodok:dev --push .

  cd:
    needs: ci
    runs-on: [self-hosted, practice]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SECRETS_SUBMODULE_ACCESS_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_DEPLOY_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEPLOY_TOKEN }}

      - name: Pull Docker image
        run: |
          echo "Docker 이미지 pull 시작"
          docker pull woowajeff/todoktodok:dev
          echo "Docker 이미지 pull 완료"

      - name: Stop running Container
        run: |
          echo "포트 80에서 실행 중인 컨테이너 확인 중..."
          container_id=$(docker ps --filter "publish=80" --format "{{.ID}}")
          if [ -n "$container_id" ]; then
            echo "컨테이너 중지: $container_id"
            docker stop $container_id
          else
            echo "중지할 컨테이너 없음 (포트 80)"
          fi

#      - name: Run docker image
#        run: |
#          echo "새 Docker 컨테이너 실행 중..."
#          docker run -d -p 80:8080 woowajeff/todoktodok:dev
#          echo "컨테이너 실행 완료"

      - name: Docker Compose Down
        run: |
          cd backend
          docker-compose down
          echo "기존 docker-compose 종료 실패 (무시)"

      - name: Docker Compose Up
        run: |
          cd backend
          docker-compose up -d
          echo "docker compose up"

      - name: Docker image Prune
        run: |
          echo "사용하지 않는 Docker 이미지 정리 중..."
          sudo docker image prune -af
          echo "이미지 정리 완료"
